name: yandex_summer_school
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"
  flutter: "3.22.2"

dependencies:
  bloc_concurrency: ^0.2.5
  bloc_test: ^9.1.7
  dio: ^5.4.3+1
  drift: ^2.18.0
  equatable: ^2.0.5
  firebase_analytics: ^11.2.0
  firebase_core: ^3.2.0
  firebase_core_platform_interface: ^5.1.0
  firebase_crashlytics: ^4.0.3
  firebase_remote_config: ^5.0.3
  flutter:
    sdk: flutter

  flutter_bloc: ^8.1.6
  flutter_localizations:
    sdk: flutter
  flutter_secure_storage: ^9.2.2
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  go_router: ^14.2.0
  intl: any
  json_annotation: ^4.9.0
  logger: ^2.3.0
  mocktail: ^1.0.4
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  sqlite3: ^2.4.3
  sqlite3_flutter_libs: ^0.5.24
  uuid: ^4.4.0

dev_dependencies:
  build_runner: ^2.4.11
  drift_dev: ^2.18.0
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  json_serializable: ^6.8.0

  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/double-exclamation-mark.png
    - assets/down-arrow.png
    - assets/dino.png
