// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDT7Ho8kkbFe2kiCbbbxRZRQtQmNiMGtbY',
    appId: '1:828795292805:web:97b3571003a3b5e06cedec',
    messagingSenderId: '828795292805',
    projectId: 'toodookeeper',
    authDomain: 'toodookeeper.firebaseapp.com',
    storageBucket: 'toodookeeper.appspot.com',
    measurementId: 'G-H0XZEJLWGH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBNt-l6FKtwzALf5frEqbOcc6ZrlAnZVCs',
    appId: '1:828795292805:android:dacea00ff17f47876cedec',
    messagingSenderId: '828795292805',
    projectId: 'toodookeeper',
    storageBucket: 'toodookeeper.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7gtOFH7n0Ix-zQRDl4GG8LTeChyWPgjY',
    appId: '1:828795292805:ios:3a5e9750cb68bb446cedec',
    messagingSenderId: '828795292805',
    projectId: 'toodookeeper',
    storageBucket: 'toodookeeper.appspot.com',
    iosBundleId: 'com.example.yandexSummerSchool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDT7Ho8kkbFe2kiCbbbxRZRQtQmNiMGtbY',
    appId: '1:828795292805:web:670daefe1ec0f2e96cedec',
    messagingSenderId: '828795292805',
    projectId: 'toodookeeper',
    authDomain: 'toodookeeper.firebaseapp.com',
    storageBucket: 'toodookeeper.appspot.com',
    measurementId: 'G-NX4FN3X1NG',
  );
}
